FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    android-tools-adb \
    python3 \
    python3-pip \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install frida-tools==12.1.2

COPY frida_relay_entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
